#!/bin/sh
echo "Running mvn clean install"
./mvnw --version
./mvnw clean install
reset
echo "Running mvn spring-boot:run"
./mvnw spring-boot:run
#./mvnw spring-boot:run -Dspring-boot.run.profiles=mi,david-remote -Dspring-boot.run.arguments=--vaadin.proKey=david@ciminc.com/pro-7c53d5b5-188b-4f2b-a4ea-3efc4b5dfc61

