/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.jvidia.aimlbda.test;

import com.jvidia.aimlbda.MyApplicationBaseTests;
import org.junit.jupiter.api.Test;

/**
 *
 * @author javau
 */
public class DdlGenerationTest extends MyApplicationBaseTests {
    @Test
    public void generateSchemaDdl() {
        // No code needed here, the DDL will be generated by the Spring Boot context loading
        // due to the properties configured in application.properties/application.yml
    }

}
