#!/bin/sh
reset
npm install -g npm
#npm ls @vaadin/react-components-pro            # final waring and package dependencies
#npm uninstall @vaadin/react-components-pro     # uninstall those not used
#rm -rf node_modules package-lock.json          # clean up
npm install react-router-dom
npm install react-dom
#yarn add react-router-dom
#npm uninstall react-scripts
#npm uninstall eslint
#npm uninstall eslint-config-react-app
npm install axios
npm install react-cookie
npm install web-vitals
npm install bootstrap
npm install reactstrap
npm install react-popper
npm install popperjs/core
npm install --save-dev @testing-library/react @testing-library/jest-dom
#npm test -- --verbose                          # run test debug
#npm test -- --watch                            # run test watch mode
npm install -g npm-check-updates
ncu                             # See available updates
ncu -u                          # Update package.json to latest versions
npm install                     # Install the updated packages
npm audit fix --force
npm fund


#The commands npm install and npm update serve different purposes in managing Node.js project dependencies.
#npm install: This command installs all the dependencies listed in your package.json file. If a package-lock.json file exists, it will use 
#    the exact versions specified there to ensure consistent installations across environments. If no node_modules directory exists or if it 
#   needs to be rebuilt, npm install will create it and populate it with the necessary packages.
#npm update: This command updates packages to their latest minor and patch versions, adhering to the version ranges specified in package.json 
#    (e.g., using ^ or ~ prefixes). It will not update packages to a new major version unless explicitly specified or if the version range allows
#    for it (e.g., *). It also updates the package-lock.json file to reflect the newly installed versions.
#Updating package.json to the Latest Versions:
#To update your package.json to reflect the absolute latest versions of all your dependencies, including major version upgrades, you can use the 
#    npm-check-updates (ncu) tool: Install npm-check-updates globally.
#    npm install -g npm-check-updates   - Install npm-check-updates globally.
#Run ncu to see available updates.
    ncu
#This command will list all packages with newer versions available but will not make any changes to your package.json.
#Update package.json with the latest versions:
    ncu -u
#This command will modify your package.json to specify the latest available versions for all your dependencies. Install the newly specified versions.
#    npm install
#After updating your package.json with ncu -u, run npm install to download and install the new versions of your packages based on the updated
#    package.json

Set up Angular Project
node -v
npm -v
npm install -g @angular/cli
ng v

ng new my-angular-app
cd my-angular-app

ng generate component dashboard
ng generate component login
ng generate interface models/user
ng generate interface models/userReponse
ng generate service guards/auth.guard
ng generate service guards/auth.service
