CREATE TABLE IF NOT EXISTS auditLogs (
    id BIGSERIAL PRIMARY KEY,
    category VARCHAR(50),
    region VARCHAR(32),
    description VARCHAR(255),
    auditValue DECIMAL(10,2),
    auditDate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

/*
Hibernate: create table auditLogs (id bigint generated by default as identity, auditDate timestamp(6) with time zone, 
    auditValue float(53), category varchar(255), description varchar(255), region varchar(255), primary key (id))
*/
