CREATE TABLE IF NOT EXISTS testUsers (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(50),
    password VARCHAR(255),
    name VARCHAR(32),
    firstName VARCHAR(50),
    lastName VARCHAR(50),
    email VARCHAR(200),
    phone VARCHAR(50),
    city VARCHAR(50),
    age INT,
    roles VARCHAR(255),
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

/*
Hibernate: create table testUsers (id bigint generated by default as identity, age integer not null, 
    city varchar(255), createdDate timestamp(6) with time zone, email varchar(255), firstName varchar(255), 
    lastName varchar(255), name varchar(255), password varchar(255), phone varchar(255), roles varchar(255), 
    updatedDate timestamp(6) with time zone, username varchar(255), primary key (id))
*/