CREATE TABLE IF NOT EXISTS userInfo (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255),
    password VARCHAR(255),
    name VARCHAR(32),
    imageUrl VARCHAR(255),
    emailVerified BOOLEAN DEFAULT FALSE,
    provider VARCHAR(32),
    providerId VARCHAR(255),
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

/*
Hibernate: create table userInfo (id bigint generated by default as identity, createdDate timestamp(6) with time zone, 
    email varchar(255), emailVerified boolean not null, imageUrl varchar(255), name varchar(255), password varchar(255), 
    provider enum ('github','google','local'), providerId varchar(255), updatedDate timestamp(6) with time zone, primary key (id))
*/