CREATE TABLE IF NOT EXISTS userRoles (
    id BIGSERIAL PRIMARY KEY,
    role_id BIGSERIAL, 
    userInfo_id BIGSERIAL
);

alter table if exists userRoles add constraint FKr8po5fcn68r4j43ygjdswug4d foreign key (role_id) references roles
;
alter table if exists userRoles add constraint FKryir9arnpwdrx8kndbx0sibxi foreign key (userInfo_id) references userInfo
;
/*
Hibernate: create table userRoles (id bigint generated by default as identity, role_id bigint, userInfo_id bigint, primary key (id))
Hibernate: alter table if exists userRoles add constraint FKr8po5fcn68r4j43ygjdswug4d foreign key (role_id) references roles
Hibernate: alter table if exists userRoles add constraint FKryir9arnpwdrx8kndbx0sibxi foreign key (userInfo_id) references userInfo
*/