CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(50),
    password VARCHAR(256),
    name VARCHAR(32),
    firstName VARCHAR(50),
    lastName VARCHAR(50),
    middleInitial VARCHAR(1),
    email VARCHAR(200),
    phone VARCHAR(50),
    city VARCHAR(50),
    birthDate TIMESTAMP WITH TIME ZONE,
    age INT,
    roles VARCHAR(50),
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

/*
Hibernate: create table users (id bigint generated by default as identity, age integer, birthDate timestamp(6) with time zone, 
    createdDate timestamp(6) with time zone, email varchar(255), firstName varchar(255), lastName varchar(255), middleInitial varchar(255), 
    name varchar(255), password varchar(255), updatedDate timestamp(6) with time zone, username varchar(255), primary key (id))
*/

